name: Facebook Manual Post

on:
  workflow_dispatch:   # bisa dijalankan manual dari Actions tab

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install puppeteer

      - name: Run bot
        run: node index.js
        env:
          COOKIE_AKUN1: ${{ secrets.COOKIE_AKUN1 }}
